name: run shell commands
on: push

jobs:
  run-spark-submit-commands:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.5.3'
          hadoop-version: '3'

<<<<<<< HEAD
      - run: spark-submit app.py
=======
      - run: spark-submit --version
>>>>>>> 1e0e83be7becfa5998dc30f10a98160352e48d1d
